#!/bin/bash
set -x
ls /usr/share/lsmcd/
cp /usr/share/lsmcd/lsmcd.service /lib/systemd/system/

mkdir -p /usr/local/lsmcd/bin
cp /usr/share/lsmcd/lsmcdctrl /usr/local/lsmcd/bin/
cp /usr/bin/lsmcd /usr/local/lsmcd/bin/